# Generated by Django 3.2.5 on 2021-07-15 14:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210715_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('from_wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payments.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='payments.wallet')),
            ],
        ),
    ]
