version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PASSWORD=postgres
      - DB_NAME=payments
      - DJANGO_SETTINGS_MODULE=django3.settings
      - WAIT_HOSTS=db:5432
    volumes:
      - .:/source
    ports:
      - "8080:8080"
    depends_on:
      - db